
[functions.meli-oauth-start]
enabled = true
verify_jwt = true
import_map = "./functions/meli-oauth-start/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/meli-oauth-start/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/meli-oauth-start/*.html" ]

[functions.meli-oauth-callback]
enabled = true
verify_jwt = true
import_map = "./functions/meli-oauth-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/meli-oauth-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/meli-oauth-callback/*.html" ]

[functions.meli-refresh-token]
enabled = true
verify_jwt = true
import_map = "./functions/meli-refresh-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/meli-refresh-token/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/meli-refresh-token/*.html" ]

[functions.meli-sync-item]
enabled = true
verify_jwt = true
import_map = "./functions/meli-sync-item/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/meli-sync-item/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/meli-sync-item/*.html" ]
